### ISSUE TITLE
Update article a index

### ISSUE THREAD

**Issue by ttsoftt** [dotaz-vspj/casopis#2]
[index.php.txt](https://github.com/user-attachments/files/17602962/index.php.txt)
[article.php.txt](https://github.com/user-attachments/files/17602965/article.php.txt)

**Comment by ttsoftt** [comment]
![WhatsApp Image 2024-11-01 at 11 31 05](https://github.com/user-attachments/assets/0b2b938f-2fca-4f80-a8e4-42cb26f5669a)
Olga píše že máme opravit patičku... viz obrázek

**Comment by ttsoftt** [comment]
A tady jsou asi nejdůležitější poslední poznámky z WA
1) Upravil jsem script article, je v příloze. 
a) Dal jsem tam Olžiny obrázky, tedy, spíše jako makety, poslala ti je? Je to tam trochu na prasáka, ale je to maketa. Kdyby Tě to žralo (chápu), předělej si.
b) upravil jsem odkazy předchozí/následující, nejde jen použít +-1, musí se vzít předchozí z db (nemusí existovat), a přidal jsem i zarážky (neexistuje->void). Uprav si případně design.
c) (jo, a v hlavičce scriptu je jen pro forma $myID=0, ale nepoužívá se, ale k té db funkci to bude potřeba - takže tuplem nehoří)

2) moc rád bych měl přímo v databázi funkci která ověří, zda má daný (přihlášený) uživatel k článku přístup - to jsou ty zakomentované konce (s sql hasAccess() 3x). Funkci mám u sebe odladěnou, jenže studenti NEMAJÍ práva na vytváření DB funkcí. Reportoval jsem Smrčkovi s prosbou o pomoc

3) článek č 3 jsem přepl z publikované verze na schválenou... pokud bude fungovat 2, uvidí ji jen přihlášení uživatelé , a to od redaktora výš a pak ti "oprávnění k článku" (autor, recenzent) - veřejně bez přihlášení by neměl být vidět

**Comment by ttsoftt** [comment]
![picture7](https://github.com/user-attachments/assets/41b79182-e7c7-4e8e-a9c5-054c703943f3)
![picture5](https://github.com/user-attachments/assets/303ed48c-47d2-4e7e-a010-679c65718388)
![picture6](https://github.com/user-attachments/assets/49c1894c-d710-41d1-88e2-eb0c999399cc)
![picture4](https://github.com/user-attachments/assets/ad88b69a-6391-455b-869b-eaf04bff13de)
![picture3](https://github.com/user-attachments/assets/6e07a215-de03-4ac4-95e5-c0f1183ad2c6)
![picture1](https://github.com/user-attachments/assets/ff77bb02-c9ac-42b5-bf73-69ca71faea10)
![picture2](https://github.com/user-attachments/assets/cf81008c-ca48-4dd1-934d-184172d60598)

**Comment by adidas-official** [comment]
- Pridal jsem index a article podle navrhu @ttsoftt 
- mensi upravy v indexu, redesign zobrazeni clanku; mozna bude potreba zobrazovat clanky v jednou sloupci z duvodu velkych rozdilu delky nazvu, poctu autoru atd.
- obrazky prosim davat do slozky /grafika a udelat push do nove vetve, tzn. zalozit novou `git checkout -b images` a udelat push do ni. Potom ji spojime s hlavni vetvi.

**Comment by adidas-official** [comment]
- obrazky na rozcestniku edice funguji
- nahrane index.php a article.php podle zadani @ttsoftt hotovo

Issue zaviram, ostatni detaily se rozpadnou do dalsich issue
