### ISSUE TITLE
Funkcionalita pro zobrazeni edic

### ISSUE THREAD

**Issue by adidas-official** [dotaz-vspj/casopis#9]
- [x] odkomentovat v sql hasAccess() funkci, propojit do query
- [x] vracet $myID (kde vsude @ttsoftt? - u vsech scriptu?)
- [x] Upravit zobrazeni obrazku

**Comment by ttsoftt** [comment]
1) odkomentování je prosté: připojit přes ".", uzavřít řádek ;, 3x v article a 1* v index; mně to fungovalo
2) moje idea byla, že se na začátku všech scriptů, kde je potenciální možnost být přihlášený, includne krátký script - něco jako startproject, nebo get_settings... a ten a) otevře sessions, b) připojí db, c) zkontroluje db-sessions jestli je zapsaná a neodlogovaná, d) načte (odkukoli) základní data do "globálních" proměných (zatím stačí to $myID, ale třeba se něco přidá?- třeba přepnutí na tmavý režim?). Protože tohle se bude stejně dělat vždycky... nebo téměř, snad jedině u loginu ne :-)
3) je to jen bezpečnostní postup, protože pokud budou obrázky, uploaduje je uživatel... a buhví, co tam pošle - na druhou stranu můžeš s tím počkat, budeme se ptát, jestli obrázky ano ne (za mne ano), takže možná ta práce bude zbytečná, pokud NE.
